from jinja2 import Template
from datetime import datetime

# HTML Template
report_template = """
<!DOCTYPE html>
<html>
<head>
    <title>VAPT Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f4f9; color: #333; }
        .container { max-width: 1200px; margin: auto; padding: 20px; background: #fff; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        h1, h2, h3 { color: #555; }
        h1 { text-align: center; }
        .summary-table, .details-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .summary-table th, .summary-table td, .details-table th, .details-table td { 
            border: 1px solid #ddd; padding: 10px; text-align: left; }
        .summary-table th, .details-table th { background-color: #f2f2f2; }
        .vulnerable { color: red; font-weight: bold; }
        .safe { color: green; font-weight: bold; }
        .recommendation { font-size: 0.9em; color: #555; margin-top: 5px; }
        .footer { text-align: center; margin-top: 20px; font-size: 0.9em; color: #888; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Vulnerability Assessment and Penetration Testing Report</h1>
        <p><strong>Report Generated On:</strong> {{ date }}</p>
        
        <h2>Summary</h2>
        <table class="summary-table">
            <thead>
                <tr>
                    <th>Vulnerability Type</th>
                    <th>Severity</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                {% for summary in summary_data %}
                <tr>
                    <td>{{ summary.vulnerability }}</td>
                    <td>{{ summary.severity }}</td>
                    <td>{{ summary.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2>Detailed Results</h2>
        {% for result in results %}
        <div class="result">
            <h3>URL/File: {{ result.url }}</h3>
            <p><strong>Vulnerability:</strong> {{ result.vulnerability }}</p>
            <p><strong>Result:</strong> <span class="{{ 'vulnerable' if 'Vulnerable' in result.result else 'safe' }}">{{ result.result }}</span></p>
            {% if result.exploit %}
            <p><strong>Exploit:</strong> {{ result.exploit }}</p>
            {% endif %}
            <p><strong>Severity:</strong> {{ result.severity }}</p>
            <p class="recommendation"><strong>Recommendation:</strong> {{ result.recommendation }}</p>
        </div>
        <hr>
        {% endfor %}
        
        <div class="footer">
            <p>Report generated by Automated VAPT Tool | © {{ date[:4] }}</p>
        </div>
    </div>
</body>
</html>
"""

# Function to Generate Report
def generate_report(results):
    # Prepare summary data
    summary_data = []
    vulnerability_count = {}

    # Aggregate counts for each vulnerability type
    for result in results:
        vulnerability = result['vulnerability']
        severity = result['severity']
        if vulnerability not in vulnerability_count:
            vulnerability_count[vulnerability] = {'count': 0, 'severity': severity}
        vulnerability_count[vulnerability]['count'] += 1

    # Format summary data
    for vuln, data in vulnerability_count.items():
        summary_data.append({
            'vulnerability': vuln,
            'severity': data['severity'],
            'count': data['count']
        })

    # Render the HTML template
    template = Template(report_template)
    report_html = template.render(
        results=results,
        summary_data=summary_data,
        date=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    )

    # Save to file
    with open('templates/report.html', 'w') as file:
        file.write(report_html)

    print("Report successfully generated: templates/report.html")
